//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::customers::Entity as Customers;
pub use super::invoices::Entity as Invoices;
pub use super::notes::Entity as Notes;
pub use super::revenues::Entity as Revenues;
pub use super::users::Entity as Users;
